baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Spyderweb Plugin Documentation'
theme = 'hugo-book'

[markup.goldmark.renderer]
  unsafe = true

[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'dark'